"""Cost simulator linked to the active Digital Twin run.

The default view prices the case attempts, actions, work orders and maintenance
requests generated by the active demo run. The older seeded planning model is
retained as an explicit alternative rather than being blended into active-run
figures.
"""

from __future__ import annotations

import pathlib
from types import SimpleNamespace
from typing import Any

import streamlit as st

from lpr_cpe_demo.benchmarks import BANDS, citation
from lpr_cpe_demo.effort import assumptions, false_positive_cost
from lpr_cpe_demo.fault_generator import generate_faults, summarise
from lpr_cpe_demo.geo_layers import (
    COST_BANDS,
    FAULT_TOOLTIP,
    OSM_ATTRIBUTION,
    OSM_POLICY_URL,
    ROUTE_CAVEAT,
    fault_records,
    road_leg_records,
    routing_summary,
)
from lpr_cpe_demo.routing import ROUTING_NOTE, router_from_env
from lpr_cpe_demo.ui import deck as deckbuild
from lpr_cpe_demo.ui import theme
from lpr_cpe_demo.ui.client import APIError
from lpr_cpe_demo.ui.common import digital_twin_api
from lpr_cpe_demo.ui.fmt import usd, usd_plain

ASSETS = pathlib.Path(__file__).resolve().parents[1] / "assets"


def _render_map(faults, show_routes: bool, router=None) -> bool:
    """Render the intervention and route map, degrading to the SVG if needed."""

    try:
        import pydeck as pdk
    except Exception as exc:
        st.warning(f"pydeck is not installed ({exc}).")
        return False
    try:
        layers = deckbuild.fault_layers(
            pdk,
            faults,
            show_routes=show_routes,
            router=router,
        )
        st.pydeck_chart(
            deckbuild.deck(pdk, layers, tooltip=FAULT_TOOLTIP),
            use_container_width=True,
        )
        return True
    except Exception as exc:
        st.warning(
            f"pydeck could not render ({type(exc).__name__}: {exc}). "
            "Falling back to the offline schematic."
        )
        return False


def _objects(rows: list[dict[str, Any]]) -> list[SimpleNamespace]:
    return [SimpleNamespace(**row) for row in rows]


def _summary_cards(faults) -> dict[str, object]:
    stats = summarise(faults)
    a, b, c, d, e = st.columns(5)
    a.metric("Case attempts", stats["faults"])
    b.metric("Modelled cost", usd_plain(float(stats["total_cost_usd"])))
    c.metric("Mean per case", usd_plain(float(stats["mean_cost_usd"])))
    d.metric("Truck rolls", stats["truck_rolls"])
    e.metric("Aggregate service exposure", f"{stats['households_affected']:,}")

    f, g, h, i = st.columns(4)
    f.metric(
        "Worked away from premise",
        stats["off_premise_interventions"],
        help="Tap, ODP, node or port interventions.",
    )
    g.metric("Dirty-boots share", f"{stats['dirty_boots_share']:.0%}")
    h.metric("Ferry jobs", stats["ferry_jobs"])
    i.metric(
        "Overnight jobs",
        stats["overnight_jobs"],
        help="Round trip plus on-site work exceeds one modelled shift.",
    )
    return stats


def _benchmark_cards(stats: dict[str, object]) -> None:
    st.info(
        f"**Benchmark cross-check.** Summing the published per-dispatch band over "
        f"the {stats['truck_rolls']} projected truck roll(s) gives "
        f"{usd(float(stats['benchmark_wasted_exposure_usd']))} if every visit were "
        f"wasted. {stats['outside_benchmark_scope']} case(s) sit outside the "
        f"published range because island travel includes ferry/overnight conditions.\n\n"
        f"{citation()}",
        icon="📊",
    )
    st.error(
        f"**Misdispatch exposure: {usd(float(stats['misdispatch_exposure_usd']))}.** "
        "This is the incremental modelled cost of sending the wrong crew first. "
        f"A false positive at the RCA gate costs "
        f"{usd(false_positive_cost().cost_usd, decimals=2)} by comparison.",
        icon="💸",
    )


def _map_and_routes(shown, *, show_routes: bool, router) -> None:
    if not _render_map(shown, show_routes, router=router):
        svg = ASSETS / "footprint_map.svg"
        if svg.exists():
            st.image(str(svg), use_container_width=True)
            st.caption(
                "pydeck unavailable; showing the offline schematic without case pins."
            )

    legend = " · ".join(label for _, _, label in COST_BANDS)
    st.caption(
        "Pin position is the **intervention point**, not the reporting address. "
        "Grey lines join a premise to its tap or ODP when work occurs elsewhere. "
        f"Pin size and colour carry cost: {legend} USD. Ringed markers are assumed "
        f"dispatch hubs. Basemap {OSM_ATTRIBUTION}, tile policy at {OSM_POLICY_URL}."
    )

    if not show_routes:
        return
    summary = routing_summary(road_leg_records(shown, router))
    if summary["all_routed"]:
        st.caption(
            f"All {summary['legs']} road leg(s) follow real roads via "
            f"{type(router).__name__}. Ferry legs remain arcs by design."
        )
    elif summary["on_roads"]:
        st.caption(
            f"{summary['on_roads']} of {summary['legs']} road leg(s) follow real "
            f"roads; {summary['straight_line']} fell back to straight lines. "
            f"{ROUTING_NOTE}"
        )
    elif summary.get("router_error"):
        st.warning(
            f"Routing was configured but every leg failed: "
            f"{summary['router_error']}. Showing straight lines. Check OSRM_URL.",
            icon="🛣",
        )
    else:
        st.caption(f"{ROUTE_CAVEAT} {ROUTING_NOTE}")


def _active_table(rows: list[dict[str, Any]]) -> None:
    st.subheader("Run-derived cost and dispatch cases")
    ordered = sorted(rows, key=lambda row: -float(row["total_cost_usd"]))
    st.dataframe(
        [
            {
                "case": row["case_id"],
                "incident": row["incident_id"],
                "service": row["service_id"],
                "scenario": row["scenario"],
                "technology": row["technology"],
                "municipio": row["municipio"],
                "domain": row["recommended_domain"],
                "action": row["executed_or_forecast_action"],
                "action status": row["action_status"],
                "cost basis": row["cost_basis"],
                "work order": row["work_order_id"],
                "MR": row["mr_id"],
                "crew": row["crew_type"],
                "base": row["base_id"].replace("BASE-", ""),
                "travel min": row["travel_minutes"],
                "cost USD": row["total_cost_usd"],
            }
            for row in ordered
        ],
        hide_index=True,
        use_container_width=True,
    )


def _active_ledger(rows: list[dict[str, Any]], *, run_id: str) -> None:
    st.subheader("Run-derived effort ledger")
    chosen = st.selectbox(
        "Case",
        [row["case_id"] for row in rows],
        format_func=lambda case_id: next(
            (
                f"{row['case_id']} — {row['scenario']} — {row['municipio']} — "
                f"{usd_plain(float(row['total_cost_usd']))}"
            )
            for row in rows
            if row["case_id"] == case_id
        ),
        key=f"cost_case_{run_id}",
    )
    row = next(item for item in rows if item["case_id"] == chosen)
    left, right = st.columns([2, 1])
    with left:
        st.dataframe(row["ledger_rows"], hide_index=True, use_container_width=True)
    with right:
        st.write(f"**Run** {row['run_id']}")
        st.write(f"**Incident** {row['incident_id']}")
        st.write(f"**Service / device** {row['service_id']} / {row['device_id']}")
        st.write(f"**Scenario** {row['scenario']}")
        st.write(
            f"**Generated action** {row['executed_or_forecast_action']} "
            f"({row['action_status']})"
        )
        st.write(f"**Worked at** {row['intervention_id']} ({row['intervention_kind']})")
        st.write(f"**Mapped municipio** {row['municipio']} ({row['archetype']})")
        st.write(f"**Crew / base** {row['crew_type']} / {row['base_name']}")
        if row["work_order_ids"]:
            st.write(f"**Work order(s)** {', '.join(row['work_order_ids'])}")
        if row["mr_ids"]:
            st.write(f"**MR(s)** {', '.join(row['mr_ids'])}")
        generated = row.get("generated_route_minutes")
        if generated is not None:
            st.write(
                f"**Travel input** {generated} generated min one way; "
                f"{row['modelled_route_minutes']} modelled route min"
            )
        else:
            st.write(f"**Travel input** {row['modelled_route_minutes']} modelled min")
        st.metric("Modelled cost", usd_plain(float(row["total_cost_usd"]), decimals=2))
        st.metric(
            "If misdispatched",
            usd_plain(float(row["misdispatch_cost_usd"]), decimals=2),
            delta=f"+{usd_plain(float(row['misdispatch_premium_usd']), decimals=2)}",
            delta_color="inverse",
        )
        st.caption(row["cost_provenance"])
        st.caption(row["location_provenance"])
        if row.get("location_warning"):
            st.warning(row["location_warning"])
        if row.get("route", {}).get("warning"):
            st.warning(row["route"]["warning"])


def _render_active_run() -> None:
    try:
        projection = digital_twin_api().dispatch_cost_projection()
    except APIError as exc:
        st.error(
            "The active Digital Twin run could not be loaded. Create or activate a "
            f"demo run first, or select Planning model below. Details: {exc}"
        )
        return

    run_id = str(projection.get("run_id", "active"))
    rows = list(projection.get("cases", []))
    if not rows:
        st.info("The active run has no generated case attempts to cost or dispatch.")
        return

    context = projection.get("measurement_context", {})
    st.success(
        f"Linked to active demo run **{projection.get('run_id')}**. "
        f"The projection contains {len(rows)} complete case attempt(s) and is not "
        "built from a paginated display response."
    )
    st.info(
        "**Mixed-provenance calculation.** Service, case, incident, RCA, action, "
        "work-order, MR, skill, parts and generated timestamps come from the demo "
        "run. Municipio coordinates and dispatch hubs are deterministic planning "
        "mappings, while labour, vehicle, ferry, overnight and parts prices remain "
        "assumed demonstration rates."
    )
    st.caption(
        f"As of {context.get('as_of') or 'run snapshot'} · grain "
        f"{context.get('primary_grain', 'case_id')} · {context.get('completeness', '')}"
    )

    first = st.columns([2, 1, 1, 1])
    scenarios = sorted({str(row["scenario"]) for row in rows})
    selected_scenarios = first[0].multiselect(
        "Generated scenarios",
        scenarios,
        default=scenarios,
        key=f"cost_scenarios_{run_id}",
    )
    technologies = ["All", *sorted({str(row["technology"]) for row in rows})]
    technology = first[1].selectbox(
        "Technology", technologies, key=f"cost_technology_{run_id}"
    )
    basis = first[2].selectbox(
        "Cost basis",
        ["All", "generated_execution", "governed_forecast"],
        format_func=lambda value: value.replace("_", " ").title(),
        key=f"cost_basis_{run_id}",
    )
    show_routes = first[3].checkbox(
        "Show dispatch routes", value=True, key=f"cost_routes_{run_id}"
    )
    second = st.columns([1, 1, 2])
    plant_only = second[0].checkbox(
        "Plant interventions only",
        help="Tap, ODP, node and access-port interventions.",
        key=f"cost_plant_{run_id}",
    )
    field_only = second[1].checkbox(
        "Field-dispatch cases only", key=f"cost_field_{run_id}"
    )
    action_statuses = sorted({str(row["action_status"]) for row in rows})
    selected_statuses = second[2].multiselect(
        "Action lifecycle",
        action_statuses,
        default=action_statuses,
        key=f"cost_status_{run_id}",
    )

    filtered = [
        row
        for row in rows
        if row["scenario"] in selected_scenarios
        and (technology == "All" or row["technology"] == technology)
        and (basis == "All" or row["cost_basis"] == basis)
        and (not plant_only or not row["intervention_is_at_premise"])
        and (not field_only or int(row["truck_rolls"]) > 0)
        and row["action_status"] in selected_statuses
    ]
    if not filtered:
        st.info("No generated cases match the current filters.")
        return

    faults = _objects(filtered)
    router = router_from_env()
    stats = _summary_cards(faults)

    generated_cost = sum(
        float(row["total_cost_usd"])
        for row in filtered
        if row["cost_basis"] == "generated_execution"
    )
    forecast_cost = sum(
        float(row["total_cost_usd"])
        for row in filtered
        if row["cost_basis"] == "governed_forecast"
    )
    split = st.columns(4)
    split[0].metric("Generated execution cost", usd_plain(generated_cost))
    split[1].metric("Governed forecast cost", usd_plain(forecast_cost))
    split[2].metric(
        "Generated work orders",
        len({item for row in filtered for item in row["work_order_ids"]}),
    )
    split[3].metric(
        "Generated MRs",
        len({item for row in filtered for item in row["mr_ids"]}),
    )

    _benchmark_cards(stats)
    _map_and_routes(faults, show_routes=show_routes, router=router)
    _active_table(filtered)
    _active_ledger(filtered, run_id=run_id)

    with st.expander("Input lineage, assumptions and benchmark source"):
        st.write("**Run-derived inputs**")
        st.json(projection.get("provenance", {}).get("run_derived", []))
        st.write("**Modelled geography and dispatch inputs**")
        st.json(projection.get("provenance", {}).get("modelled", []))
        st.write("**Assumed economic inputs**")
        st.json(assumptions())
        st.write("**Third-party benchmark bands**")
        st.json({band: BANDS[band] for band in BANDS})
        st.caption(citation())


def _render_planning_model() -> None:
    st.warning(
        "**Independent planning model.** Faults are generated from a local count and "
        "seed and are not linked to the active Digital Twin run. Rates, durations, "
        "plant ratios and hub locations are assumptions, not LPR operational data.",
        icon="⚠️",
    )
    controls = st.columns([1, 1, 1, 1])
    count = controls[0].slider("Faults", 5, 200, 40, step=5)
    seed = controls[1].number_input(
        "Seed",
        min_value=0,
        max_value=2_147_483_647,
        value=20_260_817,
        step=1,
        help="Same seed gives the same planning faults and costs.",
    )
    show_routes = controls[2].checkbox(
        "Show dispatch routes",
        value=True,
        key="planning_show_routes",
    )
    plant_only = controls[3].checkbox(
        "Plant interventions only",
        key="planning_plant_only",
    )
    faults = generate_faults(count, seed=int(seed))
    shown = (
        [fault for fault in faults if not fault.intervention_is_at_premise]
        if plant_only
        else faults
    )
    if not shown:
        st.info("No plant interventions in this planning sample.")
        return

    router = router_from_env()
    stats = _summary_cards(shown)
    _benchmark_cards(stats)
    _map_and_routes(shown, show_routes=show_routes, router=router)

    st.subheader("Planning cost by fault")
    rows = sorted(fault_records(shown), key=lambda row: -float(row["cost"]))
    st.dataframe(
        [
            {
                "fault": row["fault_id"],
                "priority": row["priority"],
                "municipio": row["municipio"],
                "technology": row["technology"],
                "domain": row["domain"],
                "intervention": row["intervention_id"],
                "crew": row["crew"],
                "base": row["base"],
                "minutes": row["minutes"],
                "cost USD": row["cost"],
                "if misdispatched USD": row["if_missed"],
            }
            for row in rows
        ],
        hide_index=True,
        use_container_width=True,
    )

    st.subheader("Planning effort ledger")
    chosen = st.selectbox(
        "Fault",
        [fault.fault_id for fault in shown],
        format_func=lambda fault_id: next(
            (
                f"{fault.fault_id} — {fault.municipio} — {fault.true_domain} — "
                f"{usd_plain(fault.total_cost_usd)}"
            )
            for fault in shown
            if fault.fault_id == fault_id
        ),
        key="planning_fault",
    )
    fault = next(item for item in shown if item.fault_id == chosen)
    left, right = st.columns([2, 1])
    with left:
        st.dataframe(list(fault.ledger_rows), hide_index=True, use_container_width=True)
    with right:
        st.write(f"**Reported by** {fault.household_id}")
        st.write(f"**Worked at** {fault.intervention_id} ({fault.intervention_kind})")
        st.write(f"**Serving** {fault.households_affected} household(s)")
        st.write(f"**Crew** {fault.crew_type} boots from {fault.base_name}")
        st.write(f"**Travel** {fault.travel_minutes} min each way")
        st.metric("Cost", usd_plain(fault.total_cost_usd, decimals=2))

    with st.expander("Planning assumptions and benchmark source"):
        st.json(assumptions())
        st.json({band: BANDS[band] for band in BANDS})
        st.caption(citation())


def render() -> None:
    st.markdown(
        theme.header(
            "Cost simulator",
            "Price the exact cases generated by the active demo run, or switch to "
            "the independent planning model for what-if analysis.",
        ),
        unsafe_allow_html=True,
    )
    source = st.radio(
        "Input source",
        ("Active demo run", "Planning model"),
        horizontal=True,
        help=(
            "Active demo run is the default and shares the persisted Digital Twin "
            "run used by Executive, Predictive and Customer Care."
        ),
    )
    if source == "Active demo run":
        _render_active_run()
    else:
        _render_planning_model()
