"""Visual identity with measured readability.

The background artwork is ORIGINAL line work generated by
`scripts/generate_landmark_band.py`: an abstract Puerto Rico motif built from a
garita silhouette and crenellated wall, the Cordillera ridgeline, a coastal
lighthouse and palm forms. No photograph is fetched or embedded, so there is no
licensing question and no network dependency.

Readability is asserted, not assumed
------------------------------------
Decorative backgrounds are the usual way a dashboard becomes unreadable. Three
rules are enforced here and checked by test:

1. Artwork appears only in the header band and as a corner watermark. It is never
   placed behind a table, a metric or body copy.
2. The watermark opacity is capped, and the composite of ink over
   artwork-over-surface is what gets measured, not the ink over a clean surface.
3. Every text colour must clear WCAG AA against the composite: 4.5:1 for body
   text, 3:1 for large text. `contrast_report()` returns the numbers so a change
   that breaks contrast fails a test rather than shipping.
"""

from __future__ import annotations

from dataclasses import dataclass

# Palette. Teals and warm tans, consistent with the map layers so the two read as
# one product.
INK = "#1C2B2B"              # body text
INK_MUTED = "#4A5A5A"        # captions
SURFACE = "#FCFBFA"          # page background
SURFACE_RAISED = "#F4F1EC"   # cards and header band
ACCENT = "#0C5457"           # hubs, headings
ACCENT_WARM = "#8F7D62"      # ferry, plant
DANGER = "#A83C32"

# Artwork is drawn in this tone. Opacity is capped so the composite stays light.
ARTWORK_INK = "#0C5457"
HEADER_ARTWORK_OPACITY = 0.10
WATERMARK_OPACITY = 0.045
MAX_ARTWORK_OPACITY = 0.12   # anything above this starts eating text contrast

WCAG_AA_BODY = 4.5
WCAG_AA_LARGE = 3.0


def hex_to_rgb(value: str) -> tuple[int, int, int]:
    v = value.lstrip("#")
    return tuple(int(v[i:i + 2], 16) for i in (0, 2, 4))  # type: ignore[return-value]


def _channel(c: int) -> float:
    s = c / 255.0
    return s / 12.92 if s <= 0.04045 else ((s + 0.055) / 1.055) ** 2.4


def relative_luminance(colour: str) -> float:
    r, g, b = (_channel(c) for c in hex_to_rgb(colour))
    return 0.2126 * r + 0.7152 * g + 0.0722 * b


def contrast_ratio(foreground: str, background: str) -> float:
    a, b = relative_luminance(foreground), relative_luminance(background)
    lighter, darker = max(a, b), min(a, b)
    return round((lighter + 0.05) / (darker + 0.05), 2)


def composite(over: str, under: str, opacity: float) -> str:
    """Flatten `over` at `opacity` onto `under`, giving the colour text sits on."""
    o, u = hex_to_rgb(over), hex_to_rgb(under)
    mixed = tuple(round(o[i] * opacity + u[i] * (1 - opacity)) for i in range(3))
    return "#{:02X}{:02X}{:02X}".format(*mixed)


@dataclass(frozen=True, slots=True)
class ContrastCheck:
    label: str
    foreground: str
    background: str
    ratio: float
    required: float

    @property
    def passes(self) -> bool:
        return self.ratio >= self.required


def contrast_report() -> list[ContrastCheck]:
    """Every text-on-background pairing the theme actually produces."""
    header_bg = composite(ARTWORK_INK, SURFACE_RAISED, HEADER_ARTWORK_OPACITY)
    watermark_bg = composite(ARTWORK_INK, SURFACE, WATERMARK_OPACITY)
    return [
        ContrastCheck("body on surface", INK, SURFACE,
                      contrast_ratio(INK, SURFACE), WCAG_AA_BODY),
        ContrastCheck("body over watermark", INK, watermark_bg,
                      contrast_ratio(INK, watermark_bg), WCAG_AA_BODY),
        ContrastCheck("caption on surface", INK_MUTED, SURFACE,
                      contrast_ratio(INK_MUTED, SURFACE), WCAG_AA_BODY),
        ContrastCheck("caption over watermark", INK_MUTED, watermark_bg,
                      contrast_ratio(INK_MUTED, watermark_bg), WCAG_AA_BODY),
        ContrastCheck("body on raised card", INK, SURFACE_RAISED,
                      contrast_ratio(INK, SURFACE_RAISED), WCAG_AA_BODY),
        ContrastCheck("heading over header artwork", ACCENT, header_bg,
                      contrast_ratio(ACCENT, header_bg), WCAG_AA_LARGE),
        ContrastCheck("body over header artwork", INK, header_bg,
                      contrast_ratio(INK, header_bg), WCAG_AA_BODY),
        ContrastCheck("danger on surface", DANGER, SURFACE,
                      contrast_ratio(DANGER, SURFACE), WCAG_AA_BODY),
    ]


def failing_checks() -> list[ContrastCheck]:
    return [c for c in contrast_report() if not c.passes]


def css(*, header_svg_data_uri: str = "", watermark_svg_data_uri: str = "",
        show_artwork: bool = True) -> str:
    """Style block.

    Artwork is confined to the header band and a fixed corner watermark behind
    everything, at capped opacity. Tables, metrics and inputs sit on opaque
    surfaces so nothing decorative shows through data.
    """
    header_layer = ""
    if show_artwork and header_svg_data_uri:
        header_layer = (
            f'background-image: url("{header_svg_data_uri}");'
            f"background-repeat: no-repeat;"
            f"background-position: right -20px center;"
            f"background-size: auto 150%;"
            f"opacity: 1;")
    watermark = ""
    if show_artwork and watermark_svg_data_uri:
        watermark = f"""
    .stApp::before {{
        content: "";
        position: fixed;
        inset: auto -4vw -6vh auto;
        width: 46vw; height: 46vh;
        background-image: url("{watermark_svg_data_uri}");
        background-repeat: no-repeat;
        background-position: bottom right;
        background-size: contain;
        opacity: {WATERMARK_OPACITY};
        pointer-events: none;
        z-index: 0;
    }}"""

    return f"""<style>
    .stApp {{ background-color: {SURFACE}; }}
    {watermark}
    /* Content sits above the watermark. */
    .block-container {{ position: relative; z-index: 1; padding-top: 1.1rem; }}

    .lpr-header {{
        position: relative;
        border-radius: 14px;
        padding: 1.1rem 1.4rem;
        margin-bottom: 1rem;
        background-color: {SURFACE_RAISED};
        border: 1px solid rgba(12, 84, 87, 0.12);
        overflow: hidden;
        {header_layer}
    }}
    .lpr-header h1, .lpr-header h2 {{
        margin: 0; color: {ACCENT}; font-size: 1.5rem; letter-spacing: -0.01em;
    }}
    .lpr-header p {{
        margin: 0.3rem 0 0; color: {INK_MUTED}; font-size: 0.9rem; max-width: 62ch;
    }}

    /* Data surfaces stay opaque: never let artwork sit behind a number. */
    [data-testid="stMetric"], [data-testid="stDataFrame"], .stDataFrame,
    [data-testid="stExpander"], [data-testid="stTable"] {{
        background-color: {SURFACE} !important;
        border: 1px solid rgba(12, 84, 87, 0.14);
        border-radius: 10px;
        position: relative; z-index: 1;
    }}
    [data-testid="stMetric"] {{ padding: 0.75rem 0.9rem; }}
    [data-testid="stMetricValue"] {{ color: {ACCENT}; }}
    h1, h2, h3 {{ color: {ACCENT}; }}
    </style>"""


def header(title: str, subtitle: str = "") -> str:
    sub = f"<p>{subtitle}</p>" if subtitle else ""
    return f'<div class="lpr-header"><h1>{title}</h1>{sub}</div>'
